"""add sent ids

Revision ID: 27b8a464f9e5
Revises: 399f3e0a94c3
Create Date: 2026-02-26 21:16:24.155908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b8a464f9e5'
down_revision: Union[str, Sequence[str], None] = '399f3e0a94c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('sent_message_id', sa.String(length=128), nullable=True))
    op.add_column('approvals', sa.Column('sent_thread_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approvals', 'sent_thread_id')
    op.drop_column('approvals', 'sent_message_id')
    # ### end Alembic commands ###
