"""add workspace_id to audit_logs

Revision ID: 39ec8246a25d
Revises: 1425364066f2
Create Date: 2026-02-26 22:16:13.934051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ec8246a25d'
down_revision: Union[str, Sequence[str], None] = '1425364066f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'workspace_id')
    # ### end Alembic commands ###
