"""add users auth

Revision ID: 5d6c26d92e0a
Revises: ac1cafd20128
Create Date: 2026-02-27 19:31:03.556958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d6c26d92e0a'
down_revision: Union[str, Sequence[str], None] = 'ac1cafd20128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_workspace_id'), 'users', ['workspace_id'], unique=False)
    op.add_column('workspaces', sa.Column('timezone', sa.String(length=64), nullable=True))
    op.add_column('workspaces', sa.Column('default_meeting_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('workspaces', sa.Column('company_tone', sa.Text(), nullable=True))
    op.add_column('workspaces', sa.Column('auto_execute_actions', sa.Boolean(), nullable=True))
    op.alter_column('workspaces', 'name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_workspaces_name'), table_name='workspaces')
    op.drop_column('workspaces', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_workspaces_name'), 'workspaces', ['name'], unique=True)
    op.alter_column('workspaces', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_column('workspaces', 'auto_execute_actions')
    op.drop_column('workspaces', 'company_tone')
    op.drop_column('workspaces', 'default_meeting_duration_minutes')
    op.drop_column('workspaces', 'timezone')
    op.drop_index(op.f('ix_users_workspace_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
