"""approval action support

Revision ID: ac1cafd20128
Revises: d0bedbd3b532
Create Date: 2026-02-27 11:08:01.473563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1cafd20128'
down_revision: Union[str, Sequence[str], None] = 'd0bedbd3b532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('action_type', sa.String(length=32), nullable=True))
    op.add_column('approvals', sa.Column('action_payload', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approvals', 'action_payload')
    op.drop_column('approvals', 'action_type')
    # ### end Alembic commands ###
