"""initial_schema

Revision ID: ccb7e14c1b83
Revises: 
Create Date: 2026-03-05 20:50:19.096491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb7e14c1b83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('token_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_tokens_id'), 'google_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_google_tokens_workspace_id'), 'google_tokens', ['workspace_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('google_email', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('default_meeting_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('company_tone', sa.Text(), nullable=True),
    sa.Column('auto_execute_actions', sa.Boolean(), nullable=True),
    sa.Column('company_display_name', sa.String(), nullable=True),
    sa.Column('company_email', sa.String(), nullable=True),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('company_phone', sa.String(), nullable=True),
    sa.Column('signature_style', sa.String(), nullable=True),
    sa.Column('signature_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=True),
    sa.Column('from_email', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('classification_label', sa.String(length=32), nullable=True),
    sa.Column('classification_confidence', sa.String(length=16), nullable=True),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('draft_reply', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('sent_message_id', sa.String(length=128), nullable=True),
    sa.Column('sent_thread_id', sa.String(length=128), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=True),
    sa.Column('action_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('audit_logs')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_google_tokens_workspace_id'), table_name='google_tokens')
    op.drop_index(op.f('ix_google_tokens_id'), table_name='google_tokens')
    op.drop_table('google_tokens')
    # ### end Alembic commands ###
