"""add google_email to workspaces

Revision ID: d3669412698b
Revises: 1d4399bfbbfc
Create Date: 2026-03-04 21:43:44.689149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3669412698b'
down_revision: Union[str, Sequence[str], None] = '1d4399bfbbfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approvals', 'workspace_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('approvals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_message_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_workspace_id'), table_name='approvals')
    op.create_foreign_key(None, 'approvals', 'workspaces', ['workspace_id'], ['id'])
    op.alter_column('audit_logs', 'workspace_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.create_foreign_key(None, 'audit_logs', 'workspaces', ['workspace_id'], ['id'])
    op.alter_column('google_tokens', 'token_json',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ux_google_tokens_workspace_id'), table_name='google_tokens')
    op.drop_column('google_tokens', 'refresh_token')
    op.drop_column('google_tokens', 'token')
    op.drop_column('google_tokens', 'client_secret')
    op.drop_column('google_tokens', 'client_id')
    op.drop_column('google_tokens', 'scopes')
    op.drop_column('google_tokens', 'token_uri')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_workspace_id'), table_name='users')
    op.alter_column('workspaces', 'signature_style',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'team'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'signature_style',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'team'::character varying"))
    op.create_index(op.f('ix_users_workspace_id'), 'users', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('google_tokens', sa.Column('token_uri', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('google_tokens', sa.Column('scopes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('google_tokens', sa.Column('client_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('google_tokens', sa.Column('client_secret', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('google_tokens', sa.Column('token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('google_tokens', sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ux_google_tokens_workspace_id'), 'google_tokens', ['workspace_id'], unique=True)
    op.alter_column('google_tokens', 'token_json',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'workspace_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.create_index(op.f('ix_approvals_workspace_id'), 'approvals', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_approvals_message_id'), 'approvals', ['message_id'], unique=False)
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.alter_column('approvals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('approvals', 'workspace_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
